name: Node.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: Install dependencies
              run: npm ci

            - name: Install Angular CLI globally
              run: npm install -g @angular/cli
            
            - name: Build Angular app
              run: ng build

            - name: Build Angular app
              run: ng build
